[package]
name = "gups"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shmem = { path = "../shmem" }
uname = "0.1.1"
rand = "0.6"