[package]
name = "symm_mem_test"
version = "0.1.0"
authors = ["Rebecca Hassett <rebecca.hassett@stonybrook.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shmem = { path = "../shmem" }
uname = "0.1.1"
